export type PlatformCategory =
  | 'SOCIAL'
  | 'STREAMING'
  | 'GAMING'
  | 'PRODUCTIVITY'
  | 'MUSIC'
  | 'NEWS'
  | 'EDUCATION'
  | 'TRAVEL'
  | 'FOOD'
  | 'SECURITY'
  | 'INVESTMENT'
  | 'ENTERTAINMENT'
  | 'HEALTH'
  | 'ADULT'
  | 'FITNESS'
  | 'SHOPPING'
  | 'OTHER';
