version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # nest-app:
  #   build:
  #     context: .
  #   container_name: nest-app
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env # ou .env.production se for produção
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: npm run start:dev # sobrescreve o CMD do Dockerfile em dev
  #   environment:
  #     - NODE_ENV=development

volumes:
  postgres_data:
