version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}

volumes:
  postgres_data:
