version: "3.8"

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    command: sh -c "npx prisma migrate deploy && npm run start:${NODE_ENV}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
