name: Deploy App

on:
  push:
    branches:
      - main  # ou 'master' dependendo do seu projeto

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: task-forge
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build e Push da imagem Docker
        run: |
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

      - name: Deploy via SSH na EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/api-task-forge
            git pull origin main
            docker-compose pull
            docker-compose up -d --remove-orphans
